### ISSUE TITLE
Typo problem in 'Closure.md'

### ISSUE THREAD

**Issue by sunshiningsoo** [yeojaeng/My_Own_Repo#5]
안녕하세요 swift closure에 대한 공부를 하다,
'completion handler' 라는 키워드로 구글을 헤매고 있을때,
https://duwjdtn11.tistory.com/520
블로그의 도움을 받았습니다.

매우 잘 정리되어 있어 이해에 정말 큰 도움이 되었습니다.🙌
글에는 Closure에 대한 추가 정리본인 GitHub 링크가 있었는데요,
https://github.com/IAnnealer/Study_Log/blob/master/iOS/Contents/Closure.md

**'Closure 는 Reference Type'** 이라는 목록에 typo error가 있는 것 같아 이슈 올리게 되었습니다!

```
var a:Int = 1
var b:Int = 0

var closure = {print(a,b)}

closure()       // 1, 0

a = 0
b - 1

closure()       // 0, 1
```

기존 상단의 코드블럭에서 **'b - 1' -> 'b = 1'** 가 되어야 더욱 클리어하게 코드의 이해를 할 수 있을 것 같습니다.

블로그의 좋은 정리글들과 양질의 지식공유 감사합니다👍

**Comment by nil-ian** [comment]
안녕하세요 :D 
내용 확인하고 수정하였습니다!
감사합니다👍ㅎㅎ
